export const ETHERSCAN_V2_URLS: Record<number, { explorerUrl: string; apiUrl: string }> = {
  1: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1", explorerUrl: "https://etherscan.io" },
  10: { apiUrl: "https://api.etherscan.io/v2/api?chainid=10", explorerUrl: "https://optimistic.etherscan.io/" },
  25: { apiUrl: "https://api.etherscan.io/v2/api?chainid=25", explorerUrl: "https://cronoscan.com" },
  50: { apiUrl: "https://api.etherscan.io/v2/api?chainid=50", explorerUrl: "https://xdcscan.com/" },
  51: { apiUrl: "https://api.etherscan.io/v2/api?chainid=51", explorerUrl: "https://testnet.xdcscan.com/" },
  56: { apiUrl: "https://api.etherscan.io/v2/api?chainid=56", explorerUrl: "https://bscscan.com" },
  97: { apiUrl: "https://api.etherscan.io/v2/api?chainid=97", explorerUrl: "https://testnet.bscscan.com" },
  100: { apiUrl: "https://api.etherscan.io/v2/api?chainid=100", explorerUrl: "https://gnosisscan.io/" },
  130: { apiUrl: "https://api.etherscan.io/v2/api?chainid=130", explorerUrl: "https://uniscan.xyz/" },
  137: { apiUrl: "https://api.etherscan.io/v2/api?chainid=137", explorerUrl: "https://polygonscan.com" },
  146: { apiUrl: "https://api.etherscan.io/v2/api?chainid=146", explorerUrl: "https://sonicscan.org/" },
  199: { apiUrl: "https://api.etherscan.io/v2/api?chainid=199", explorerUrl: "https://bttcscan.com/" },
  204: { apiUrl: "https://api.etherscan.io/v2/api?chainid=204", explorerUrl: "https://opbnb.bscscan.com/" },
  252: { apiUrl: "https://api.etherscan.io/v2/api?chainid=252", explorerUrl: "https://fraxscan.com/" },
  300: { apiUrl: "https://api.etherscan.io/v2/api?chainid=300", explorerUrl: "https://sepolia-era.zksync.network/" },
  324: { apiUrl: "https://api.etherscan.io/v2/api?chainid=324", explorerUrl: "https://era.zksync.network/" },
  480: { apiUrl: "https://api.etherscan.io/v2/api?chainid=480", explorerUrl: "https://worldscan.org/" },
  999: { apiUrl: "https://api.etherscan.io/v2/api?chainid=999", explorerUrl: "https://hyperevmscan.io/" },
  1028: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1028", explorerUrl: "https://testnet.bttcscan.com/" },
  1101: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1101", explorerUrl: "https://zkevm.polygonscan.com/" },
  1111: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1111", explorerUrl: "https://wemixscan.com/" },
  1112: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1112", explorerUrl: "https://testnet.wemixscan.com/" },
  1284: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1284", explorerUrl: "https://moonbeam.moonscan.io/" },
  1285: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1285", explorerUrl: "https://moonriver.moonscan.io/" },
  1287: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1287", explorerUrl: "https://moonbase.moonscan.io/" },
  1301: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1301", explorerUrl: "https://sepolia.uniscan.xyz/" },
  1923: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1923", explorerUrl: "https://swellchainscan.io/" },
  1924: { apiUrl: "https://api.etherscan.io/v2/api?chainid=1924", explorerUrl: "https://sepolia.swellchainscan.io/" },
  2442: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=2442",
    explorerUrl: "https://cardona-zkevm.polygonscan.com/",
  },
  2522: { apiUrl: "https://api.etherscan.io/v2/api?chainid=2522", explorerUrl: "https://holesky.fraxscan.com/" },
  2741: { apiUrl: "https://api.etherscan.io/v2/api?chainid=2741", explorerUrl: "https://abscan.org/" },
  4801: { apiUrl: "https://api.etherscan.io/v2/api?chainid=4801", explorerUrl: "https://sepolia.worldscan.org/" },
  5000: { apiUrl: "https://api.etherscan.io/v2/api?chainid=5000", explorerUrl: "https://mantlescan.xyz/" },
  5003: { apiUrl: "https://api.etherscan.io/v2/api?chainid=5003", explorerUrl: "https://sepolia.mantlescan.xyz/" },
  5611: { apiUrl: "https://api.etherscan.io/v2/api?chainid=5611", explorerUrl: "https://opbnb-testnet.bscscan.com/" },
  8453: { apiUrl: "https://api.etherscan.io/v2/api?chainid=8453", explorerUrl: "https://basescan.org" },
  10143: { apiUrl: "https://api.etherscan.io/v2/api?chainid=10143", explorerUrl: "https://testnet.monadscan.com/" },
  11124: { apiUrl: "https://api.etherscan.io/v2/api?chainid=11124", explorerUrl: "https://sepolia.abscan.org/" },
  17000: { apiUrl: "https://api.etherscan.io/v2/api?chainid=17000", explorerUrl: "https://sepolia.etherscan.io" },
  33111: { apiUrl: "https://api.etherscan.io/v2/api?chainid=33111", explorerUrl: "https://curtis.apescan.io/" },
  33139: { apiUrl: "https://api.etherscan.io/v2/api?chainid=33139", explorerUrl: "https://apescan.io/" },
  42161: { apiUrl: "https://api.etherscan.io/v2/api?chainid=42161", explorerUrl: "https://arbiscan.io" },
  42170: { apiUrl: "https://api.etherscan.io/v2/api?chainid=42170", explorerUrl: "https://nova.arbiscan.io/" },
  42220: { apiUrl: "https://api.etherscan.io/v2/api?chainid=42220", explorerUrl: "https://celoscan.io" },
  43113: { apiUrl: "https://api.etherscan.io/v2/api?chainid=43113", explorerUrl: "https://testnet.snowscan.xyz/" },
  43114: { apiUrl: "https://api.etherscan.io/v2/api?chainid=43114", explorerUrl: "https://snowscan.xyz/" },
  43521: { apiUrl: "https://api.etherscan.io/v2/api?chainid=43521", explorerUrl: "https://testnet.memecorescan.io/" },
  44787: { apiUrl: "https://api.etherscan.io/v2/api?chainid=44787", explorerUrl: "https://alfajores.celoscan.io/" },
  50104: { apiUrl: "https://api.etherscan.io/v2/api?chainid=50104", explorerUrl: "https://sophscan.xyz/" },
  57054: { apiUrl: "https://api.etherscan.io/v2/api?chainid=57054", explorerUrl: "https://testnet.sonicscan.org/" },
  59141: { apiUrl: "https://api.etherscan.io/v2/api?chainid=59141", explorerUrl: "https://sepolia.lineascan.build/" },
  59144: { apiUrl: "https://api.etherscan.io/v2/api?chainid=59144", explorerUrl: "https://lineascan.build/" },
  80002: { apiUrl: "https://api.etherscan.io/v2/api?chainid=80002", explorerUrl: "https://amoy.polygonscan.com/" },
  80069: { apiUrl: "https://api.etherscan.io/v2/api?chainid=80069", explorerUrl: "https://testnet.berascan.com/" },
  80094: { apiUrl: "https://api.etherscan.io/v2/api?chainid=80094", explorerUrl: "https://berascan.com/" },
  81457: { apiUrl: "https://api.etherscan.io/v2/api?chainid=81457", explorerUrl: "https://blastscan.io/" },
  84532: { apiUrl: "https://api.etherscan.io/v2/api?chainid=84532", explorerUrl: "https://sepolia.basescan.org/" },
  167000: { apiUrl: "https://api.etherscan.io/v2/api?chainid=167000", explorerUrl: "https://taikoscan.io/" },
  167009: { apiUrl: "https://api.etherscan.io/v2/api?chainid=167009", explorerUrl: "https://hekla.taikoscan.io/" },
  421614: { apiUrl: "https://api.etherscan.io/v2/api?chainid=421614", explorerUrl: "https://sepolia.arbiscan.io/" },
  534351: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=534351",
    explorerUrl: "https://sepolia.scrollscan.com/",
  },
  534352: { apiUrl: "https://api.etherscan.io/v2/api?chainid=534352", explorerUrl: "https://scrollscan.com/" },
  560048: { apiUrl: "https://api.etherscan.io/v2/api?chainid=560048", explorerUrl: "https://hoodi.etherscan.io/" },
  660279: { apiUrl: "https://api.etherscan.io/v2/api?chainid=660279", explorerUrl: "https://xaiscan.io/" },
  11155111: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=11155111",
    explorerUrl: "https://sepolia.etherscan.io",
  },
  11155420: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=11155420",
    explorerUrl: "https://sepolia-optimism.etherscan.io/",
  },
  168587773: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=168587773",
    explorerUrl: "https://sepolia.blastscan.io/",
  },
  531050104: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=531050104",
    explorerUrl: "https://testnet.sophscan.xyz/",
  },
  37714555429: {
    apiUrl: "https://api.etherscan.io/v2/api?chainid=37714555429",
    explorerUrl: "https://sepolia.xaiscan.io/",
  },
}
