export const ETHERSCAN_V2_URLS: Record<number, { explorerUrl: string; apiUrl: string }> = {
  1: { explorerUrl: "https://etherscan.io", apiUrl: "https://api.etherscan.io/v2/api?chainid=1" },
  11155111: {
    explorerUrl: "https://sepolia.etherscan.io",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=11155111",
  },
  17000: { explorerUrl: "https://sepolia.etherscan.io", apiUrl: "https://api.etherscan.io/v2/api?chainid=17000" },
  560048: { explorerUrl: "https://hoodi.etherscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=560048" },
  56: { explorerUrl: "https://bscscan.com", apiUrl: "https://api.etherscan.io/v2/api?chainid=56" },
  97: { explorerUrl: "https://testnet.bscscan.com", apiUrl: "https://api.etherscan.io/v2/api?chainid=97" },
  137: { explorerUrl: "https://polygonscan.com", apiUrl: "https://api.etherscan.io/v2/api?chainid=137" },
  80002: { explorerUrl: "https://amoy.polygonscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=80002" },
  1101: { explorerUrl: "https://zkevm.polygonscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1101" },
  2442: {
    explorerUrl: "https://cardona-zkevm.polygonscan.com/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=2442",
  },
  8453: { explorerUrl: "https://basescan.org", apiUrl: "https://api.etherscan.io/v2/api?chainid=8453" },
  84532: { explorerUrl: "https://sepolia.basescan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=84532" },
  42161: { explorerUrl: "https://arbiscan.io", apiUrl: "https://api.etherscan.io/v2/api?chainid=42161" },
  42170: { explorerUrl: "https://nova.arbiscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=42170" },
  421614: { explorerUrl: "https://sepolia.arbiscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=421614" },
  59144: { explorerUrl: "https://lineascan.build/", apiUrl: "https://api.etherscan.io/v2/api?chainid=59144" },
  59141: { explorerUrl: "https://sepolia.lineascan.build/", apiUrl: "https://api.etherscan.io/v2/api?chainid=59141" },
  81457: { explorerUrl: "https://blastscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=81457" },
  168587773: {
    explorerUrl: "https://sepolia.blastscan.io/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=168587773",
  },
  10: { explorerUrl: "https://optimistic.etherscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=10" },
  11155420: {
    explorerUrl: "https://sepolia-optimism.etherscan.io/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=11155420",
  },
  43114: { explorerUrl: "https://snowscan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=43114" },
  43113: { explorerUrl: "https://testnet.snowscan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=43113" },
  199: { explorerUrl: "https://bttcscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=199" },
  1028: { explorerUrl: "https://testnet.bttcscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1028" },
  42220: { explorerUrl: "https://celoscan.io", apiUrl: "https://api.etherscan.io/v2/api?chainid=42220" },
  44787: { explorerUrl: "https://alfajores.celoscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=44787" },
  25: { explorerUrl: "https://cronoscan.com", apiUrl: "https://api.etherscan.io/v2/api?chainid=25" },
  252: { explorerUrl: "https://fraxscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=252" },
  2522: { explorerUrl: "https://holesky.fraxscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=2522" },
  100: { explorerUrl: "https://gnosisscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=100" },
  5000: { explorerUrl: "https://mantlescan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=5000" },
  5003: { explorerUrl: "https://sepolia.mantlescan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=5003" },
  43521: { explorerUrl: "https://testnet.memecorescan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=43521" },
  1284: { explorerUrl: "https://moonbeam.moonscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1284" },
  1285: { explorerUrl: "https://moonriver.moonscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1285" },
  1287: { explorerUrl: "https://moonbase.moonscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1287" },
  204: { explorerUrl: "https://opbnb.bscscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=204" },
  5611: { explorerUrl: "https://opbnb-testnet.bscscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=5611" },
  534352: { explorerUrl: "https://scrollscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=534352" },
  534351: {
    explorerUrl: "https://sepolia.scrollscan.com/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=534351",
  },
  167000: { explorerUrl: "https://taikoscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=167000" },
  167009: { explorerUrl: "https://hekla.taikoscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=167009" },
  1111: { explorerUrl: "https://wemixscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1111" },
  1112: { explorerUrl: "https://testnet.wemixscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1112" },
  324: { explorerUrl: "https://era.zksync.network/", apiUrl: "https://api.etherscan.io/v2/api?chainid=324" },
  300: { explorerUrl: "https://sepolia-era.zksync.network/", apiUrl: "https://api.etherscan.io/v2/api?chainid=300" },
  660279: { explorerUrl: "https://xaiscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=660279" },
  37714555429: {
    explorerUrl: "https://sepolia.xaiscan.io/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=37714555429",
  },
  50: { explorerUrl: "https://xdcscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=50" },
  51: { explorerUrl: "https://testnet.xdcscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=51" },
  33139: { explorerUrl: "https://apescan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=33139" },
  33111: { explorerUrl: "https://curtis.apescan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=33111" },
  480: { explorerUrl: "https://worldscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=480" },
  4801: { explorerUrl: "https://sepolia.worldscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=4801" },
  50104: { explorerUrl: "https://sophscan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=50104" },
  531050104: {
    explorerUrl: "https://testnet.sophscan.xyz/",
    apiUrl: "https://api.etherscan.io/v2/api?chainid=531050104",
  },
  146: { explorerUrl: "https://sonicscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=146" },
  57054: { explorerUrl: "https://testnet.sonicscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=57054" },
  130: { explorerUrl: "https://uniscan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=130" },
  1301: { explorerUrl: "https://sepolia.uniscan.xyz/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1301" },
  2741: { explorerUrl: "https://abscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=2741" },
  11124: { explorerUrl: "https://sepolia.abscan.org/", apiUrl: "https://api.etherscan.io/v2/api?chainid=11124" },
  80094: { explorerUrl: "https://berascan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=80094" },
  80069: { explorerUrl: "https://testnet.berascan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=80069" },
  1923: { explorerUrl: "https://swellchainscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1923" },
  1924: { explorerUrl: "https://sepolia.swellchainscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=1924" },
  10143: { explorerUrl: "https://testnet.monadscan.com/", apiUrl: "https://api.etherscan.io/v2/api?chainid=10143" },
  999: { explorerUrl: "https://hyperevmscan.io/", apiUrl: "https://api.etherscan.io/v2/api?chainid=999" },
}
